### ISSUE TITLE
Users GET requests, for both collection and single user by UUID, return an empty array.

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Authentication#7]
`{{authentication}}{{environment}}/users`
```
[
    [],
    [],
    [],
    [],
    [],
    [],
    []
]
```

`{{authentication}}{{environment}}/users/{uuid}`
```
[]
```

**Comment by baddlan** [comment]
Worth nothing also that Postman sample of the PUT request to {{authentication}}{{environment}}/users/{{uuid}}
also fails to update the User entity even after adding an email property.

**Comment by mario-digitalstate** [comment]
This was related to missing permissions for your user. Data fixtures have been added.
